# Generated by Django 2.2.5 on 2019-10-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2019, 10, 19, 15, 15, 25, 568681)),
        ),
    ]
